
#define LED_OFF 0
#define LED_1  1
#define LED_2  (1 << 1)
#define LED_3  (1 << 2)
#define LED_4  (1 << 3)
#define LED_5  (1 << 4)
#define LED_6  (1 << 5)
#define LED_7  (1 << 6)
#define LED_8  (1 << 7)
#define LED_9  (1 << 8)
#define LED_10 (1 << 9)
#define LED_11 (1 << 10)
#define LED_12 (1 << 11)
#define LED_ALL 0xFFFF

#define NUM_FRAMES 109

PROGMEM prog_uint16_t FRAMES[NUM_FRAMES] = {
  LED_6,
  LED_OFF,
  LED_6,
  LED_OFF,
  LED_6,
  LED_OFF,
  LED_6,
  LED_OFF,
  LED_6,
  LED_6,
  LED_OFF,
  LED_6,
  LED_6,
  LED_OFF,
  LED_6,
  LED_6,
  LED_OFF,
  LED_6,
  LED_6,
  LED_6,
  LED_6,
  LED_6,
  LED_6,
  LED_6,
  LED_6,
  LED_6,
  LED_6,
  LED_6,
  LED_6,
  LED_6,
                                  LED_6,
                          LED_5 | LED_6 | LED_7,
                  LED_4 | LED_5 | LED_6 | LED_7 | LED_8,
          LED_3 | LED_4 | LED_5 | LED_6 | LED_7 | LED_8 | LED_9,
  LED_2 | LED_3 | LED_4 | LED_5 | LED_6 | LED_7 | LED_8 | LED_9 | LED_10,
  LED_ALL,
  LED_ALL,
  LED_2 | LED_3 | LED_4 | LED_5 | LED_6 | LED_7 | LED_8 | LED_9 | LED_10,
          LED_3 | LED_4 | LED_5 | LED_6 | LED_7 | LED_8 | LED_9,
                  LED_4 | LED_5 | LED_6 | LED_7 | LED_8,
                          LED_5 | LED_6 | LED_7,
                                  LED_6,
                          LED_5 | LED_6 | LED_7,
                  LED_4 | LED_5 | LED_6 | LED_7 | LED_8,
          LED_3 | LED_4 | LED_5 | LED_6 | LED_7 | LED_8 | LED_9,
  LED_2 | LED_3 | LED_4 | LED_5 | LED_6 | LED_7 | LED_8 | LED_9 | LED_10,
  LED_ALL,
  LED_2 | LED_3 | LED_4 | LED_5 | LED_6 | LED_7 | LED_8 | LED_9 | LED_10 | LED_11,
          LED_3 | LED_4 | LED_5 | LED_6 | LED_7 | LED_8 | LED_9 | LED_10 | LED_11,
                  LED_4 | LED_5 | LED_6 | LED_7 | LED_8 |         LED_10 | LED_11,
                          LED_5 | LED_6 | LED_7 |                 LED_10 | LED_11,
                                  LED_6 |                         LED_10 | LED_11,
                                  LED_6 |                         LED_10 | LED_11,
                                  LED_6 |                         LED_10 | LED_11,
                                  LED_6 |                         LED_10 | LED_11,
                                  LED_6 |                         LED_10 | LED_11,
                                  LED_6 |                         LED_10 | LED_11,
                                  LED_6 |                         LED_10 | LED_11,
  LED_OFF,
                                  LED_6 |                         LED_10 | LED_11,
                                  LED_6 |                         LED_10 | LED_11,
  LED_OFF,
                                  LED_6 |                         LED_10 | LED_11,
                                  LED_6 |                         LED_10 | LED_11,
  LED_OFF,
                                  LED_6 |                         LED_10 | LED_11,
                                  LED_6 |                         LED_10 | LED_11,
  LED_OFF,
                                                                  LED_10 | LED_11,
                                                                  LED_10 | LED_11,
                                                                  LED_10 | LED_11,
                                                                  LED_10 | LED_11,
                                                                  LED_10 | LED_11,
  LED_OFF,
  LED_OFF,
  LED_OFF,
  LED_OFF,
  LED_OFF,
                                  LED_6,
                                                                  LED_10 | LED_11,
  LED_OFF,
  LED_ALL,
  LED_OFF,
  LED_ALL,
  LED_OFF,
  LED_ALL,
  LED_OFF,
  LED_ALL,
  LED_OFF,
  LED_ALL,
  LED_OFF,
  LED_ALL,
  LED_OFF,
  LED_ALL,
  LED_OFF,
  LED_ALL,
  LED_OFF,
  LED_ALL,
  LED_OFF,
  LED_ALL,
  LED_OFF,
  LED_ALL,
  LED_OFF,
  LED_ALL,
  LED_OFF,
  LED_OFF,
  LED_OFF,
  LED_OFF,
  LED_OFF,
};
